spring.application.name=SpringEcom

spring.datasource.url=jdbc:mysql://localhost:3306/telusko
spring.datasource.username=root
spring.datasource.password=Karan@4533

spring.jpa.hibernate.ddl-auto=update
